nl:
  early_access:
    title: Wil je er vroeg bij zijn?
    text: >-
      Begin 2026 verwelkomen we onze eerste gebruikers voor een gesloten bèta.
      Actieve bètagebruikers die feedback geven, ontvangen een levenslang
      gratis account.
    cta: >-
      Geïnteresseerd? Schrijf je hieronder in voor de wachtlijst.
    disclaimer: >-
      Ongeveer één keer per maand sturen we updates over de wachtlijst. Geen
      spam.
  locale_switcher:
    label: Taal switcher
  main_menu:
    title: Hoofd
  shared:
    footer:
      copyright: © %{year} Fearless Living Under Creative Knowledge S.L.
      principles: Gebouwd in Spanje – Gehost in de EU – Geen investeerders, geen AI
      info:
        title: Info
        about: Over ons
        brand: Merkmateriaal
        code_of_conduct: Gedragscode
        contact: Contact
        privacy_policy: Privacy- & Cookiebeleid
        terms_of_service: Servicevoorwaarden
        waitlist: De wachtlijst
      social:
        title: Sociaal
        bluesky: Bluesky
        codeberg: Codeberg
        discord: Discord
        discourse: Community
        email: E-mail
        github: GitHub
        linkedin: LinkedIn
        mastodon: Mastodon
        rss: RSS
      newsletter:
        title: Nieuwsbrief
        text: >-
          Elke maand sturen we een nieuwsbrief over de ontwikkelingen. Korte,
          overzichtelijke e-mails.
        disclaimer: >-
          Geen tracking, geen spam.
    subscription_form:
      button_variants:
        newsletter: 'Inschrijven'
        waitlist: 'Aanmelden'
      success: >-
        Bedankt voor je inschrijving! We hebben een e-mail met een link naar
        %{email} gestuurd om je inschrijving te bevestigen.
  theme_switcher:
    toggle: 'Schakel tussen licht en donker thema'
