nl:
  global:
    alts:
      tem_values: De ethische stap - eerlijkheid + verantwoordelijkheid + vertrouwen + transparantie + integriteit + rechtvaardigheid
    buttons:
      skip_link: Spring naar hoofdinhoud
    labels:
      honeypot: Laat dit veld alsjeblieft leeg
      website: Website of sociaal profiel
    links:
      back_home: ‚Üê Terug naar home
    menu:
      item:
        about: Over
        waitlist: Wachtlijst
