en:
  global:
    buttons:
      skip_link: Skip to main content
    labels:
      honeypot: Please leave this blank
      website: Website or social profile
    links:
      back_home: ‚Üê Head back to home
    menu:
      item:
        about: About
        waitlist: Waitlist
