nl:
  code_of_conduct:
    index_page:
      page_title: Gedragscode.
      page_description: >-
        Onze Gedragscode schetst de communitystandaarden voor respectvolle
        deelname, inclusief aangemoedigd gedrag, beperkt gedrag,
        rapportageprocedures en handhavingsrichtlijnen om een gastvrije,
        veilige en rechtvaardige omgeving voor alle leden te behouden.
      text: |
        # Gedragscode

        ## Onze Belofte

        We beloven onze community gastvrij, veilig en rechtvaardig te maken voor iedereen.

        We zijn toegewijd aan het bevorderen van een omgeving die de waardigheid, rechten en bijdragen van alle individuen respecteert en bevordert, ongeacht kenmerken zoals ras, etniciteit, kaste, huidskleur, leeftijd, fysieke kenmerken, neurodiversiteit, handicap, geslacht, genderidentiteit of -expressie, seksuele geaardheid, taal, filosofie of religie, nationale of sociale afkomst, sociaaleconomische positie, opleidingsniveau of andere status. Dezelfde deelnamerechten worden uitgebreid naar iedereen die te goeder trouw en in overeenstemming met dit Convenant deelneemt.


        ## Aangemoedigd Gedrag

        Hoewel we verschillen in sociale normen erkennen, streven we er allemaal naar te voldoen aan de verwachtingen van onze community voor positief gedrag. We begrijpen ook dat onze woorden en acties anders kunnen worden geïnterpreteerd dan we bedoelen, afhankelijk van cultuur, achtergrond of moedertaal.

        Met deze overwegingen in gedachten, komen we overeen om bewust met elkaar om te gaan en te handelen op manieren die onze gedeelde waarden centraal stellen, waaronder:

        1. Het **doel van onze community**, onze activiteiten en onze manieren van samenkomen respecteren.
        2. **Vriendelijk en eerlijk** met anderen omgaan.
        3. **Verschillende standpunten** en ervaringen respecteren.
        4. **Verantwoordelijkheid nemen** voor onze acties en bijdragen.
        5. Sierlijk **constructieve feedback** geven en ontvangen.
        6. Ons committeren aan het **herstellen van schade** wanneer deze optreedt.
        7. Op andere manieren gedragen die het **welzijn van onze community** bevorderen en in stand houden.


        ## Beperkt Gedrag

        We komen overeen het volgende gedrag in onze community te beperken. Voorvallen, bedreigingen en bevordering van dit gedrag zijn schendingen van deze Gedragscode.

        1. **Intimidatie.** Het schenden van expliciet uitgedrukte grenzen of het vertonen van onnodige persoonlijke aandacht na een duidelijk verzoek om te stoppen.
        2. **Karakteraanvallen.** Het maken van beledigende, vernederende of denigrerende opmerkingen gericht aan een communitylid of groep mensen.
        3. **Stereotypering of discriminatie.** Het karakteriseren van iemands persoonlijkheid of gedrag op basis van onveranderlijke identiteiten of eigenschappen.
        4. **Seksualisering.** Gedragen op een manier die over het algemeen als ongepast intiem zou worden beschouwd in de context of het doel van de community.
        5. **Schenden van vertrouwelijkheid**. Het delen of handelen naar iemands persoonlijke of privéinformatie zonder hun toestemming.
        6. **Gevaarverhoging.** Het veroorzaken, aanmoedigen of bedreigen van geweld of andere schade jegens een persoon of groep.
        7. Op andere manieren gedragen die **het welzijn bedreigen** van onze community.

        ### Andere Beperkingen

        1. **Misleidende identiteit.** Zich voordoen als iemand anders om welke reden dan ook, of doen alsof je iemand anders bent om handhavingsacties te ontwijken.
        2. **Niet crediteren van bronnen.** Bronnen van content die je bijdraagt niet correct vermelden.
        3. **Promotiemateriaal**. Het delen van marketing of andere commerciële content op een manier die buiten de normen van de community valt.
        4. **Onverantwoordelijke communicatie.** Het niet verantwoordelijk presenteren van content die andere beperkte gedragingen bevat, linkt naar of beschrijft.


        ## Een Probleem Melden

        Spanningen kunnen ontstaan tussen communityleden, zelfs wanneer ze hun best doen om samen te werken. Niet elk conflict vertegenwoordigt een schending van de gedragscode, en deze Gedragscode versterkt aangemoedigd gedrag en normen die kunnen helpen conflicten te vermijden en schade te minimaliseren.

        Wanneer een incident zich voordoet, is het belangrijk om dit snel te melden. Om een mogelijke schending te melden, stuur ons een e-mail op abuse@fluck.site.

        Community Moderators nemen meldingen van schendingen serieus en zullen alle moeite doen om tijdig te reageren. Ze onderzoeken alle meldingen van schendingen van de gedragscode, waarbij ze berichten, logs en opnames bekijken, of getuigen en andere deelnemers interviewen. Community Moderators houden onderzoeks- en handhavingsacties zo transparant mogelijk, terwijl ze veiligheid en vertrouwelijkheid prioriteit geven. Om deze waarden te eren, worden handhavingsacties privé uitgevoerd met de betrokken partijen, maar communicatie naar de hele community kan deel uitmaken van een wederzijds overeengekomen oplossing.


        ## Schade Aanpakken en Herstellen

        Als een onderzoek door de Community Moderators vaststelt dat deze Gedragscode is geschonden, kan de volgende handhavingsladder worden gebruikt om te bepalen hoe schade het beste kan worden hersteld, gebaseerd op de impact van het incident op de betrokken individuen en de community als geheel. Afhankelijk van de ernst van een schending kunnen lagere sporten op de ladder worden overgeslagen.

        1. **Waarschuwing**
            1. Gebeurtenis: Een schending betreffende een enkel incident of reeks incidenten.
            2. Gevolg: Een privé, schriftelijke waarschuwing van de Community Moderators.
            3. Herstel: Voorbeelden van herstel zijn onder andere een privé schriftelijke verontschuldiging, erkenning van verantwoordelijkheid en verduidelijking zoeken over verwachtingen.
        2. **Tijdelijk Beperkte Activiteiten**
            1. Gebeurtenis: Een herhaald voorval van een schending die eerder resulteerde in een waarschuwing, of het eerste voorval van een ernstiger schending.
            2. Gevolg: Een privé, schriftelijke waarschuwing met een tijdelijk beperkte afkoelperiode die is ontworpen om de ernst van de situatie te benadrukken en de betrokken communityleden tijd te geven om het incident te verwerken. De afkoelperiode kan beperkt zijn tot bepaalde communicatiekanalen of interacties met bepaalde communityleden.
            3. Herstel: Voorbeelden van herstel kunnen zijn het aanbieden van excuses, de afkoelperiode gebruiken om na te denken over acties en impact, en zorgvuldig nadenken over het opnieuw betreden van communityruimtes na afloop van de periode.
        3. **Tijdelijke Schorsing**
            1. Gebeurtenis: Een patroon van herhaalde schendingen die de Community Moderators hebben geprobeerd aan te pakken met waarschuwingen, of een enkele ernstige schending.
            2. Gevolg: Een privé schriftelijke waarschuwing met voorwaarden voor terugkeer na schorsing. Over het algemeen geven tijdelijke schorsingen de geschorste persoon tijd om na te denken over hun gedrag en mogelijke corrigerende acties.
            3. Herstel: Voorbeelden van herstel zijn onder andere het respecteren van de geest van de schorsing, voldoen aan de gespecificeerde voorwaarden voor terugkeer, en zorgvuldig nadenken over hoe opnieuw te integreren met de community wanneer de schorsing is opgeheven.
        4. **Permanente Ban**
            1. Gebeurtenis: Een patroon van herhaalde schendingen van de gedragscode die andere stappen op de ladder niet hebben kunnen oplossen, of een schending zo ernstig dat de Community Moderators bepalen dat er geen manier is om de community veilig te houden met deze persoon als lid.
            2. Gevolg: Toegang tot alle communityruimtes, tools en communicatiekanalen wordt verwijderd. Over het algemeen moeten permanente bans zelden worden gebruikt, moeten ze sterke redenering achter zich hebben, en mogen ze alleen als laatste redmiddel worden ingezet als het doorwerken van andere remedies het gedrag niet heeft kunnen veranderen.
            3. Herstel: Er is geen mogelijk herstel in gevallen van deze ernst.

        Deze handhavingsladder is bedoeld als richtlijn. Het beperkt niet het vermogen van Community Managers om hun discretie en oordeel te gebruiken, waarbij de belangen van onze community voorop staan.


        ## Reikwijdte

        Deze Gedragscode is van toepassing binnen alle communityruimtes, en is ook van toepassing wanneer een individu officieel de community vertegenwoordigt in publieke of andere ruimtes. Voorbeelden van het vertegenwoordigen van onze community zijn het gebruik van een officieel e-mailadres, posten via een officieel social media-account, of optreden als aangewezen vertegenwoordiger bij een online of offline evenement.


        ## Bronvermelding

        Deze Gedragscode is aangepast van het Contributor Covenant, versie 3.0, permanent beschikbaar op [https://www.contributor-covenant.org/version/3/0/](https://www.contributor-covenant.org/version/3/0/).

        Contributor Covenant wordt beheerd door de Organization for Ethical Source en is gelicenseerd onder CC BY-SA 4.0. Om een kopie van deze licentie te bekijken, bezoek [https://creativecommons.org/licenses/by-sa/4.0/](https://creativecommons.org/licenses/by-sa/4.0/)

        Voor antwoorden op veelgestelde vragen over Contributor Covenant, zie de FAQ op [https://www.contributor-covenant.org/faq](https://www.contributor-covenant.org/faq). Vertalingen zijn beschikbaar op [https://www.contributor-covenant.org/translations](https://www.contributor-covenant.org/translations). Aanvullende handhavings- en communityrichtlijnen zijn te vinden op [https://www.contributor-covenant.org/resources](https://www.contributor-covenant.org/resources). De handhavingsladder werd geïnspireerd door het werk van [Mozilla's code of conduct team](https://github.com/mozilla/inclusion).
